### PR TITLE
Preparing p-aap.dev.superdesk.org

### PR DESCRIPTION
**Pull request by naspeh**
@hlmnrmr asked me to prepare new dev instance for AAP project: p-aap.dev.superdesk.org

this is required changes to run our Bamboo scripts

Building history: https://bamboo.sourcefabric.org/browse/SD-DSOD161-10

### CODE REVIEW

**Comment by pavlovicnemanja** [comment]
:+1:

**Comment by naspeh** [comment]
Checked on Bamboo: https://bamboo.sourcefabric.org/browse/SD-DSOD161-10

**Comment by mdhaman** [comment]
:+1:

**Comment by naspeh** [comment]
I can't merge it, don't have access, please could you do this?

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
