### PR TITLE
Use TestCase from superdesk.tests

### PR DESCRIPTION
**Pull request by naspeh**
Regarding: https://github.com/superdesk/superdesk-core/pull/566

Also, I sorted imports in touched files according to [Google Python Style Guide.](https://google.github.io/styleguide/pyguide.html?showone=Imports_formatting#Imports_formatting)

### CODE REVIEW

**Comment by naspeh** [comment]
**It should pass after updating core references.**

**Comment by petrjasek** [comment]
@naspeh you can try to update it and we will see how it goes

**Comment by naspeh** [comment]
@petrjasek thanks, it is passed now

**Comment by mdhaman** [comment]
:+1:

**Pull request merged**
