### PR TITLE
SD-4980 : The caption/description of an image should remain italic if…

### PR DESCRIPTION
**Pull request by naomiaro**
… text is pasted there

### CODE REVIEW

**Comment by akintolga** [comment]
This solves the copy paste across fields but I think this change may break copy/cut paste within body field. If a user has a italic section and if that section is cut and pasted within the body field the `<i>` tag will be lost. This is not a problem for AAP but NTB or PA may get affected.

**Comment by naomiaro** [comment]
Yeah I was thinking of that. Really depends if copying text within the body should maintain the styling or not. I'm not sure how best to separate them if it depends if text is coming to one editor from another. Maybe this ticket isn't even valid then? Maybe people do want to copy html markup to the image description. If not maybe it's best to have an image description not even use the medium text editor and just have the text as plain and always styled with italic @akintolga . It's a bit vague what should be achieved overall here. 

@petrjasek perhaps the editor config shouldn't be the same for all fields within the system?

**Comment by naomiaro** [comment]
it could be best perhaps if handled with separate configs, where the medium editor for a description here does clean everything on paste, but then the main body_html field will not do so.

**Comment by petrjasek** [comment]
yep I guess we should figure out how it should work plus separate config for different fields

**Comment by mdhaman** [comment]
@naomiaro closing this PR as it is not needed.

**Pull request closed without merging**
